select * from appointments;
select * from billing;
select * from doctors;
select * from patients;
select  * from treatments;

# 1) Total appointments
select count(distinct appointment_id) from appointments;

# 2) Total patients visited in Hospital
select count(distinct patient_id) from appointments;

# 3) Total doctors in Hospital
select count(distinct doctor_id) from appointments;

# 4) total patients per doctor 
select doctor_id, count(distinct patient_id) as total_patient from appointments
group by doctor_id;

# 5) Total  amount by payment method
select  payment_method,round(sum(amount),2) as total_amount from billing
group by payment_method;

# 6) all doctors with specialization and year of experience
select doctor_id,concat(first_name ," ", last_name)as Doctor_name,specialization,years_experience from doctors;

# 7) All patient name and address and registration date in hospital
select patient_id,concat(first_name," ",last_name)as patient_name,address,registration_date
from patients;

# 8) Total Revenue Generated by Each Doctor
select d.doctor_id , concat(d.first_name , " ",d.last_name) as doctor_name, round(sum(b.amount),2) as total_revenue 
from doctors d join appointments a 
on d.doctor_id = a.doctor_id
join treatments t 
on a.appointment_id = t.appointment_id
join billing b
on t.treatment_id = b.treatment_id
group by d.doctor_id,concat(d.first_name , " ",d.last_name)
order by d.doctor_id;

# 9) Top 3 Doctors by revenue
select d.doctor_id , concat(d.first_name , " ",d.last_name) as doctor_name, round(sum(b.amount),2) as total_revenue 
from doctors d join appointments a 
on d.doctor_id = a.doctor_id
join treatments t 
on a.appointment_id = t.appointment_id
join billing b
on t.treatment_id = b.treatment_id
group by d.doctor_id,concat(d.first_name , " ",d.last_name)
order by total_revenue desc
limit 3;


# 10) Total Appointments by Status
select status ,count(distinct appointment_id) as total_appointment from appointments
group by status;

# 11) Total Appointments per Month
select monthname(appointment_date), count(appointment_id) from appointments
 group by month(appointment_date),monthname(appointment_date)
 order by month(appointment_date);


# 12) Average Treatment Cost per treatment , heighest first .
select treatment_type,round(avg(cost),2)as avg_cost from treatments
group by treatment_type
order by avg_cost desc;

# 13) Most Common Treatment Type
select treatment_type,round(avg(cost),2)as avg_cost from treatments
group by treatment_type
order by avg_cost desc
limit 1;

# 14) Patients Who Have Not Paid Their Bills
select p.patient_id,concat(p.first_name," ",p.last_name)as patient_name, b.payment_status from patients p
join billing b 
on p.patient_id = b.patient_id
where b.payment_status = 'pending';

# 15) Doctors with More Than 5 Years of Experience
select doctor_id,concat(first_name," ",last_name)as Doctor_name,years_experience from doctors
where years_experience > 5
order by years_experience;

# 16) Patients with Multiple Appointments
select p.patient_id,concat(p.first_name," ",p.last_name) as patient_name,count(a.appointment_id)
from patients p join appointments a 
on p.patient_id = a.patient_id
group by p.patient_id,concat(p.first_name," ",p.last_name) 
having count(a.appointment_id) > 1;

# 17) Revenue Generated per Payment Status
select payment_status,round(sum(amount),2) from billing
group by payment_status;

# 18) Top 3 Doctors by Number of Patients
select d.doctor_id,d.first_name,d.last_name,count(p.patient_id)as total_patient
from doctors d join appointments a 
on d.doctor_id = a.doctor_id
join patients p 
on a.patient_id = p.patient_id
group by d.doctor_id,d.first_name,d.last_name
order by total_patient desc
limit 3;   

# 19) Patients with Insurance Provider Details
select first_name,last_name,insurance_provider,insurance_number from patients
where insurance_provider is not null;

# 20) Appointments with Doctor and Patient Names
select a.appointment_id,
concat(p.first_name," ",p.last_name) as patient_name,
concat(d.first_name," ",d.last_name) as doctor_name,a.appointment_date,a.status
from patients p join appointments a 
on p.patient_id = a.patient_id
join doctors d 
on a.doctor_id = d.doctor_id ;

# 21) Total Revenue Collected by Each Payment Method per Month
select month(bill_date) as  month_number,payment_method,round(SUM(amount),2) as total_amount
from billing
group by month(bill_date), payment_method
order by month_number;

# 22) Find Doctors Who Have Treated More Than 5 Patients
with abc as(select a.doctor_id,count(a.patient_id) as total_patient from appointments a group by a.doctor_id)
select d.doctor_id ,concat(d.first_name," ", d.last_name)as doctor_name, total_patient
from doctors d join abc b
on b.doctor_id = d.doctor_id
where total_patient > 5
order by total_patient asc;